/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BrandLogos: typeof import('./components/BrandLogos.vue')['default']
    DoomGuy: typeof import('./components/DoomGuy.vue')['default']
    FormatDate: typeof import('./components/FormatDate.vue')['default']
    GlobalFooter: typeof import('./components/GlobalFooter.vue')['default']
    GlobalHeader: typeof import('./components/GlobalHeader.vue')['default']
    ImageLoader: typeof import('./components/ImageLoader.vue')['default']
    JournalImage: typeof import('./components/JournalImage.vue')['default']
    JournalIntro: typeof import('./components/JournalIntro.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Music: typeof import('./components/Music.vue')['default']
    PageTitle: typeof import('./components/PageTitle.vue')['default']
    ParallaxCard: typeof import('./components/ParallaxCard.vue')['default']
    PostList: typeof import('./components/PostList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skateboard: typeof import('./components/Skateboard.vue')['default']
  }
}
